// All these will be passed in from somewhere (apis?) just temp data for now

export const assets = {
  beach: "/assets/voya-beach.png",
  alaska: "/assets/voya-alaska.jpg",
  aurora: "/assets/voya-aurora.jpg",
  lake: "/assets/voya-lake.jpg",
  trees: "/assets/voya-trees.jpg",
  alaskaView: "/assets/voya-alaska-view.png",
  activity1: "/assets/voya-activity1.png",
  activity2: "/assets/voya-activity2.png",
  activity3: "/assets/voya-activity3.png",
  activity4: "/assets/voya-activity4.png",
  map: "/assets/voya-map.png",
  villa: "/assets/voya-villa.jpg",
  amalfi: "/assets/voya-amalfi.png",
  kyoto: "/assets/voya-kyoto.png",
  river: "/assets/voya-river.png",
  tower: "/assets/voya-tower.png",
  market: "/assets/voya-market.png",
  coast: "/assets/voya-coast.png",
  stonehenge: "/assets/voya-stonehenge.png",
  oxford: "/assets/voya-oxford.png",
  mountainView: "/assets/voya-mountain-view.jpg",
  gallery1: "/assets/voya-gallery1.jpg",
  gallery2: "/assets/voya-gallery2.jpg",
  gallery3: "/assets/voya-gallery3.jpg",
  gallery4: "/assets/voya-gallery4.jpg",
  basemap: "/assets/voya-basemap.png",
  profile: "/assets/voya-profile.jpg",
};